### ISSUE TITLE
Sometimes score is Nan

### ISSUE THREAD

**Issue by JakeRuth** [sheab/circle-game#1]
Hey sheab
First off, this game is awesome really nice work!
I have been playing it for a bit, it's really addictive!  Unfortunately when I broke my record I received a score of Nan points.
![fungame1](https://cloud.githubusercontent.com/assets/7349551/9288904/e03a9ffe-432b-11e5-8896-a9eef21ce2d3.png)

-Jake

**Comment by JakeRuth** [comment]
After putting in some 'debugging' lines I discovered that intermittently there is a what I believe to be a timing issue with the rendering.  The bug is that the death() function is called, but somehow when the mouse is moving really fast when the user dies the detectCollision method is called a few more times, then the radius property on the person 'obejct' becomes undefined.  (See image attached, I had bebug lines around the increment of the Person.radius, and before the "pts" message) 
![fungame1](https://cloud.githubusercontent.com/assets/7349551/9289125/a79c866e-4333-11e5-9010-22a917ae07e6.png)

I am going to fix it and create a merge request :)

**Comment by JakeRuth** [comment]
merge request: https://github.com/sheab/circle-game/pull/2

**Comment by sheab** [comment]
fixed :)
